spring:
  datasource:
    url: jdbc:mysql://localhost:3306/twitter_clone?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: mysqlMysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000