package com.example.demo.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;


/**
 * This class represents users.
 *
 * @author yosuk
 *
 */
@Entity
@Table(name = "users",uniqueConstraints = {
		@UniqueConstraint(columnNames = {
				"username"
		}),
		@UniqueConstraint(columnNames = {
				"userId"
		})
})
public class User {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@NotBlank
	@Size(max = 15)
	private String userId;

	@NotBlank
	@Size(max = 40)
	private String username;

	@NotBlank
	@Size(max = 100)
	private String password;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_roles",
			joinColumns = @JoinColumn(name = "user_id"),
			inverseJoinColumns = @JoinColumn(name = "role_id"))
	private Set<Role> roles = new HashSet<Role>();



	public User() {
	}

	/**
	 * Constructs an <code>User</code> object.
	 * @param id 			Primary Key. A long number that generated by our API for identifying  users.
	 * @param username		A string that created by users and in order to name themselves.
	 * @param userId		A string that created by users for identifying themselves.
	 * @param password		A string that created by users.
	 */
	public User(Long id, @NotBlank @Size(max = 15) String userId, @NotBlank @Size(max = 40) String username,
			@NotBlank @Size(max = 100) String password) {
		this.id = id;
		this.userId = userId;
		this.username = username;
		this.password = password;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Role> getRoles() {
		return roles;
	}

	/**
	 * Sets the roles
	 * @param roles
	 */
	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}





}
